### ISSUE TITLE
Duplicate keys in ScottoSplit vial keymap

### ISSUE THREAD

**Issue by pavel-skymill** [joe-scotto/scottokeebs#11]
The bug is present both in the pre-built hex and in the QMK config files - keys on the bottom left alpha row are duplicate (Z,X). Took me a couple of resoldering sessions before I found it :)

This is easily fixed by change below
```
+++ b/ScottoSplit/QMK/keymaps/vial/vial.json
@@ -89,7 +89,7 @@
                     "y": -0.75,
                     "x": -1.75
                 },
-                "2,1",
+                "2,0",
                 {
                     "x": 3
                 },
```
Can't create branches or make PRs in the repo so it's on you!

**Comment by joe-scotto** [comment]
Thank you, fixed in b2f5c4d769bceafe888ad4d53b6469e0fa1bca2e and c10b9c4b6fd144bf4e423b6f7bfee976903992cb.
