### ISSUE TITLE
3D files for Scotto34 PCB Edition?

### ISSUE THREAD

**Issue by bobwulff** [joe-scotto/scottokeebs#12]
https://github.com/joe-scotto/scottokeebs/tree/main/Scotto34/PCB

**Comment by joe-scotto** [comment]
I made the decision for my PCB boards to close-source everything but the firmware since I release all my [handwired](https://scottokeebs.com/blogs/keyboards) boards completely free. 

That said, the Scotto34 is simple enough to design a case on your own if you wanted :)
