### ISSUE TITLE
Release Bambu Studio file for your keycaps?

### ISSUE THREAD

**Issue by Avaviel** [joe-scotto/scottokeebs#19]
I am attempting to print your keycaps in multicolors, but I'm having issues with the import. Some of the files import to the program badly, and move around. Could you happen to share your 3mf file for the keycaps? 

https://github.com/joe-scotto/scottokeebs/tree/main/Extras/ScottoCaps/Scooped/MX/Legends

**Comment by joe-scotto** [comment]
It already exists here: https://github.com/joe-scotto/scottokeebs/blob/main/Extras/ScottoCaps/Scooped/MX/Alphas.3mf

I won't be adding anything additionally though, it's a lot of work to manage all that but this should be a good enough start.
