### ISSUE TITLE
Unable to see Placeholder Symbols

### ISSUE THREAD

**Issue by justinreddick** [joe-scotto/scottokeebs#20]
I recently downloaded the repo to start learning KiCAD and started following the PCB Desgin playlist. I was unable to find the Placehodler_ objects used in the videos although the files have them defined (i.e Placeholder_Diode is missing)
![placeholder_missing](https://github.com/user-attachments/assets/fb434c63-7093-4e64-a108-0dd02582d4ee)

**Comment by joe-scotto** [comment]
This is a Kicad but that still hasn't been fixed. Instead of searching for the footprint or symbol you need, manually scroll to the library and open it. Everything should be there if you keep the search bar empty.
