### ISSUE TITLE
Latest Scotto 9 plate files missing screw holes

### ISSUE THREAD

**Issue by ValerianClerc** [joe-scotto/scottokeebs#8]
The [latest commit to the Scotto 9](https://github.com/joe-scotto/scottokeebs/commit/64fd981946e17bfb1748774849abb6b54c125160) case/plate `.stl` files has removed the screw holes in the plate.

[Before](https://github.com/joe-scotto/scottokeebs/blob/6471538663b09b30d701e398841e1ddb5251c313/Scotto9/Case/Scotto9%20-%20Plate.stl):
![image](https://user-images.githubusercontent.com/36084793/232927184-3c93a922-cd04-47d1-a59a-72e0881a9ecc.png)

[After](https://github.com/joe-scotto/scottokeebs/blob/main/Scotto9/Case/Scotto9%20-%20Plate.stl) (current):
![image](https://user-images.githubusercontent.com/36084793/232927149-1b728b93-0187-442f-857f-b58e72fc7549.png)

**Comment by joe-scotto** [comment]
Thank you, fixed in [d236eca](https://github.com/joe-scotto/scottokeebs/commit/d236eca8e393410f7d84a18d1b41dc769da98818).
